[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["tests*"]

[project]
name = "mc_protocol"
<<<<<<< HEAD
version = "1.0.1.dev3"
=======
version = "1.0.2"
>>>>>>> origin/main
authors = [
    { name = "c2yz", email = "c2yzawa@outlook.com" },
]
description = "A quick and easy-to-use library for Minecraft things on Python. "
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.0",
<<<<<<< HEAD
    "cryptography",
    "nbt"
=======
    "pycryptodome"
>>>>>>> origin/main
]


[project.urls]
Homepage = "https://github.com/c2yz-awa/mc_protocol"
Repository = "https://github.com/c2yz-awa/mc_protocol"